#!/usr/bin/env php
<?php

$root = dirname(__FILE__);

require_once $root . '/vendor/squizlabs/php_codesniffer/autoload.php';
/*
$argv = [ $_SERVER['argv'][0] ];
$argv[] = '--config-set';
$argv[] = 'installed_paths';
$argv[] = implode(',', array(
    $root . '/vendor/wp-coding-standards/wpcs/',
    $root . '/justcoded/',
));

// patch command options to add new paths
$_SERVER['argc'] += 3;
$_SERVER['argv'][] = '--config-set';
$_SERVER['argv'][] = 'installed_paths';
$_SERVER['argv'][] = implode(',', array(
    $root . '/vendor/wp-coding-standards/wpcs/',
    $root . '/justcoded/',
));
*/
$runner   = new PHP_CodeSniffer\Runner();
$exitCode = $runner->runPHPCS();
exit($exitCode);
